import os
import re
import sys

def camel_to_snake(name):
    # Converts CamelCase to snake_case
    name = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', name).lower()

def parse_header(filepath):
    entities = []
    try:
        with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()
    except Exception:
        return []

    class_matches = re.finditer(r'(class|struct)\s+([A-Za-z0-9_]+)\s*(:[^{]+)?\{', content)

    for class_match in class_matches:
        class_name = class_match.group(2)
        class_snake = camel_to_snake(class_name)

        start_pos = class_match.end()
        brace_count = 1
        end_pos = start_pos
        while brace_count > 0 and end_pos < len(content):
            if content[end_pos] == '{': brace_count += 1
            elif content[end_pos] == '}': brace_count -= 1
            end_pos += 1

        class_body = content[start_pos:end_pos]

        public_sections = re.split(r'\b(private|protected):', class_body)
        public_content = public_sections[0]
        for i in range(1, len(public_sections), 2):
            if public_sections[i-1] == 'public':
                public_content += public_sections[i]

        method_matches = re.findall(r'\b([A-Za-z0-9_]+)\s*\([^)]*\)\s*(?:const)?\s*(?:override|final)?\s*;', public_content)
        for method in method_matches:
            if method not in ('if', 'for', 'while', 'switch', 'return', 'catch', 'throw', 'u32', 'u16', 's32', 'v3f'):
                entities.append(f"{class_snake}.{camel_to_snake(method)}")

        prop_matches = re.findall(r'\b(?:[A-Za-z0-9_<>:*]+)\s+([A-Za-z0-9_]+)\s*=', public_content)
        prop_matches += re.findall(r'\b(?:[A-Za-z0-9_<>:*]+)\s+([A-Za-z0-9_]+)\s*;', public_content)
        for prop in prop_matches:
            if prop not in ('public', 'private', 'protected', 'virtual', 'const', 'static', 'return', 'explicit', 'friend'):
                entities.append(f"{class_snake}.{camel_to_snake(prop)}")

    return list(set(entities))

def main(src_dir, output_file):
    all_paths = set()
    for root, dirs, files in os.walk(src_dir):
        if any(x in root for x in ['myengine', 'benchmark', 'unittest', 'lib', 'irr']):
            continue
        for file in files:
            if file.endswith('.h'):
                paths = parse_header(os.path.join(root, file))
                all_paths.update(paths)

    os.makedirs(os.path.dirname(output_file), exist_ok=True)

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write('// Auto-generated by scanner.py. Do not edit.\n')
        f.write('#include "myengine/registry.h"\n\n')
        f.write('void register_generated_paths() {\n')
        for path in sorted(all_paths):
            f.write(f'    Registry::register_path("{path}");\n')
        f.write('}\n')

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: scanner.py <src_dir> <output_file>")
        sys.exit(1)
    main(sys.argv[1], sys.argv[2])
